name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Start Selenoid Server
      uses: Xotabu4/selenoid-github-action@v1
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
    - name: Run yarn install and web app
      run: |
        cd shopping
        git submodule init
        git submodule update
        yarn install
        yarn run dev
