name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Start Selenoid Server
      uses: Xotabu4/selenoid-github-action@v1
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
    - name: Run yarn install
      run: yarn install
    - name: Run web app
      run: yarn run dev
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Run
      run: dotnet run --project ./CourseWork/CourseWork.csproj
