name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    needs: selenoid
    
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Start Selenoid Server
      uses: Xotabu4/selenoid-github-action@v1
    - name: Run web app
      run: |
        cd shopping
        docker build -t shopping .
        docker run -dp 3000:3000 shopping
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.x'
    - name: Run tests
      run: dotnet run --project ./CourseWork/CourseWork.csproj
