name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run web app
      working-directory: ./shopping
      run: |
        git submodule init
        git submodule update
        docker build -t shopping .
        docker-compose up -d
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.x'
    - name: Run tests
      run: dotnet run --project ./CourseWork/CourseWork.csproj
    - name: Stop shopping
      working-directory: ./shopping
      run: |
        docker-compose stop
